NCEPLIBS-g2tmpl: g2sec4_temp11.f90 File Reference
g2sec4_temp11.f90 File Reference
Returns the Grib2 Section 4 Template 4.11 list for given keys.
Functions/Subroutines
subroutine g2sec4_temp11 (icatg, iparm, typ_gen_proc_key, gen_proc_or_mod_key, hrs_obs_cutoff, min_obs_cutoff, unit_of_time_key, fcst_time, lvl_type1, scale_fac1, scaled_val1, lvl_type2, scale_fac2, scaled_val2, type_ens_fcst_key, perturb_num, num_fcst_ens, year_intvl, mon_intvl, day_intvl, hour_intvl, min_intvl, sec_intvl, num_time_range, stat_miss_val, type_of_stat_proc, type_of_time_inc, stat_unit_time_key, leng_time_range_stat, stat_unit_time_key_succ, time_inc_betwn_succ_fld, ipdstmpl11)
This subroutine returns the Grib2 Section 4 Template 4.11 list for given keys PDT 4.11 - Individual ensemble forecast, control and perturbed, at a horizontal level or in a horizontal layer, in a continuous or non-continuous time interval.
Detailed Description
Returns the Grib2 Section 4 Template 4.11 list for given keys.
Author
Boi Vuong
Date
2015-01-09
Definition in file g2sec4_temp11.f90.
Function/Subroutine Documentation
g2sec4_temp11()
subroutine g2sec4_temp11 (integer(4), intent(in) icatg, integer(4), intent(in) iparm, character(len=*), intent(in) typ_gen_proc_key, character(len=*), intent(in) gen_proc_or_mod_key, integer(4), intent(in) hrs_obs_cutoff, integer(4), intent(in) min_obs_cutoff, character(len=*), intent(in) unit_of_time_key, integer(4), intent(in) fcst_time, character(len=*), intent(in) lvl_type1, integer(4), intent(in) scale_fac1, integer(4), intent(in) scaled_val1, character(len=*), intent(in) lvl_type2, integer(4), intent(in) scale_fac2, integer(4), intent(in) scaled_val2, character(len=*), intent(in) type_ens_fcst_key, integer(4), intent(in) perturb_num, integer(4), intent(in) num_fcst_ens, integer(4), intent(in) year_intvl, integer(4), intent(in) mon_intvl, integer(4), intent(in) day_intvl, integer(4), intent(in) hour_intvl, integer(4), intent(in) min_intvl, integer(4), intent(in) sec_intvl, integer(4), intent(in) num_time_range, integer(4), intent(in) stat_miss_val, character(len=*), intent(in) type_of_stat_proc, character(len=*), intent(in) type_of_time_inc, character(len=*), intent(in) stat_unit_time_key, integer(4), intent(in) leng_time_range_stat, character(len=*), intent(in) stat_unit_time_key_succ, integer(4), intent(in) time_inc_betwn_succ_fld, integer(4), dimension(32), intent(inout) ipdstmpl11)
This subroutine returns the Grib2 Section 4 Template 4.11 list for given keys PDT 4.11 - Individual ensemble forecast, control and perturbed, at a horizontal level or in a horizontal layer, in a continuous or non-continuous time interval.
Parameters
[in] icatg Parameter category (see Code Table 4.1)
[in] iparm Parameter number (see Code Table 4.2)
[in] typ_gen_proc_key Type of generating process (see Code Table 4.3)
[in] gen_proc_or_mod_key Analysis or forecast generating process identified (see Code ON388 Table A)
[in] hrs_obs_cutoff Hours after reference time data cutoff (see Note 1)
[in] min_obs_cutoff Minutes after reference time data cutoff
[in] unit_of_time_key Indicator of unit of time range (see Code Table 4.4)
[in] fcst_time Forecast time in units defined by octet 18 (see Note 2)
[in] lvl_type1 Type of first fixed surface (see Code Table 4.5)
[in] scale_fac1 Scale factor of first fixed surface
[in] scaled_val1 Scaled value of first fixed surface
[in] lvl_type2 Type of second fixed surfaced (see Code Table 4.5)
[in] scale_fac2 Scale factor of second fixed surface
[in] scaled_val2 Scaled value of second fixed surfaces
[in] type_ens_fcst_key Type of ensemble forecast (see Code table 4.6)
[in] perturb_num Perturbation ensemble number
[in] num_fcst_ens number of forecasts in ensemble
[in] year_intvl Year Time of end of overall time interval
[in] mon_intvl Month Time of end of overall time interval
[in] day_intvl Day Time of end of overall time interval
[in] hour_intvl Hour Time of end of overall time interval
[in] min_intvl Minute Time of end of overall time interval
[in] sec_intvl Second Time of end of overall time interval
[in] num_time_range n number of time ranges specifications describing the time intervals used to calculate the statistically-processed field
[in] stat_miss_val Total number of data values missing in statistical process Specification of the outermost (or only) time range over which statistical processing is done
[in] type_of_stat_proc Statistical process used to calculate the processed field from the field at each time increment during the time range (see Code Table 4.10)
[in] type_of_time_inc Type of time increment between successive fields used in the statistical processing (see Code Table 4.11)
[in] stat_unit_time_key Indicator of unit of time for time range over which statistical processing is done (see Code Table 4.4)
[in] leng_time_range_stat Length of the time range over which statistical processing is done, in units defined by the previous octet
[in] stat_unit_time_key_succ Indicator of unit of time for the increment between the successive fields used (see Code table 4.4)
[in] time_inc_betwn_succ_fld Time increment between successive fields, in units defined by the previous octet (see Notes 3 & 4)
[out] ipdstmpl11 GRIB2 PDS Template 4.11 listing
Author
Boi Vuong
Date
2015-01-09
Definition at line 55 of file g2sec4_temp11.f90.
References grib2_all_tables_module::get_g2_fixedsurfacetypes(), grib2_all_tables_module::get_g2_on388genproc(), grib2_all_tables_module::get_g2_statprocesstypes(), grib2_all_tables_module::get_g2_typeofensfcst(), grib2_all_tables_module::get_g2_typeofgenproc(), grib2_all_tables_module::get_g2_typeoftimeintervals(), and grib2_all_tables_module::get_g2_unitoftimerange().