NCEPLIBS-g2tmpl: grib2_all_tables_module Module Reference
grib2_all_tables_module Module Reference
Define the variables in the derived data type discipline provided in Section 0.
Data Types
type fixed_surface_types
type gen_proc
type local_table_vers_no
type order_of_sptdiff_vals
type origin_centers
type prod_status
type sigreftime
type statistical_processing_types
type subcenters
type type_of_aerosol
type type_of_cluster
type type_of_compression
type type_of_data
type type_of_derive_fcst
type type_of_ens_fcst
type type_of_gen_proc
type type_of_intervals
type type_of_orig_field_vals
type type_of_packingmethod
type type_of_precip
type type_of_prob
type type_of_time_intervals
type unit_of_time_range
type version_no
Functions/Subroutines
subroutine g2sec0 (idisc, listsec0)
This subroutine returns the section 0 list for a given discipline value.
subroutine g2sec1 (origin_key, subcen_key, vers_key, lvers_key, sigreftime_key, refyear_val, refmon_val, refday_val, refhour_val, refmin_val, refsec_val, prodstatus_key, typeofdata_key, listsec1)
This subroutine returns the section 1 list for given keys.
subroutine g2sec4_temp0 (icatg, iparm, typ_gen_proc_key, gen_proc_or_mod_key, hrs_obs_cutoff, min_obs_cutoff, unit_of_time_key, fcst_time, lvl_type1, scale_fac1, scaled_val1, lvl_type2, scale_fac2, scaled_val2, ipdstmpl0)
This subroutine returns the Grib2 Section 4 Template 4.0 list for given keys PDT 4.0 - Analysis or forecast at a horizontal level or in a horizontal layer at a point in time.
subroutine g2sec4_temp44 (icatg, iparm, aer_type, typ_intvl_size, scale_fac1_size, scale_val1_size, scale_fac2_size, scale_val2_size, typ_gen_proc_key, gen_proc_or_mod_key, hrs_obs_cutoff, min_obs_cutoff, unit_of_time_key, fcst_time, lvl_type1, scale_fac1, scaled_val1, lvl_type2, scale_fac2, scaled_val2, ipdstmpl44)
This subroutine returns the Grib2 Section 4 Template 4.44 list for given keys PDT 4.44 - Analysis or forecast at a horizontal level or in a horizontal layer at a point in time for aerosol.
subroutine g2sec4_temp48 (icatg, iparm, aer_type, typ_intvl_size, scale_fac1_size, scale_val1_size, scale_fac2_size, scale_val2_size, typ_intvl_wavelength, scale_fac1_wavelength, scale_val1_wavelength, scale_fac2_wavelength, scale_val2_wavelength, typ_gen_proc_key, gen_proc_or_mod_key, hrs_obs_cutoff, min_obs_cutoff, unit_of_time_key, fcst_time, lvl_type1, scale_fac1, scaled_val1, lvl_type2, scale_fac2, scaled_val2, ipdstmpl48)
This subroutine returns the Grib2 Section 4 Template 4.0 list for given keys PDT 4.48 - Analysis or forecast at a horizontal level or in a horizontal layer at a point in time for aerosol.
subroutine g2sec4_temp8 (icatg, iparm, typ_gen_proc_key, gen_proc_or_mod_key, hrs_obs_cutoff, min_obs_cutoff, unit_of_time_key, fcst_time, lvl_type1, scale_fac1, scaled_val1, lvl_type2, scale_fac2, scaled_val2, year_intvl, mon_intvl, day_intvl, hour_intvl, min_intvl, sec_intvl, num_time_range, stat_miss_val, type_of_stat_proc, type_of_time_inc, stat_unit_time_key, leng_time_range_stat, stat_unit_time_key_succ, time_inc_betwn_succ_fld, ipdstmpl8)
This subroutine returns the Grib2 Section 4 Template 4.8 list for given keys PDT 4.8 - Average, accumulation, extreme values or other statistically processed values at a horizontal level or in a horizontal layer in a continuous or non-continuous time interval.
subroutine g2sec5_temp0 (dec_scale_fac, bin_scale_fac, tlnumbits, ifield5)
This subroutine returns the section 5 list array for a given decimal scale factor (D) and type of original field values (Table 5.1) value from GRIB2 - GRID Template 5.0 Grid point data - simple packing.
subroutine g2sec5_temp2 (dec_scale_fac, bin_scale_fac, ifield5)
This subroutine returns the section 5 list array with a given binary, and decimal scale factor from GRIB2 - GRID Template 5.2 Grid point data - complex packing.
subroutine g2sec5_temp3 (dec_scale_fac, bin_scale_fac, order_of_sptdiff, ifield5)
This subroutine returns the section 5 list array with a given binary, and decimal scale factor from GRIB2 - GRID Template 5.3 Grid point data - complex packing with spatial difference.
subroutine g2sec5_temp40 (dec_scale_fac, bin_scale_fac, tlnumbits, type_of_compression, ifield5)
This subroutine returns the section 5 list array for a given decimal scale factor (D),type of original field value (Table 5.40) and type of compression used from GRIB2 - GRID Template 5.40 Grid point data - JPEG 2000 Code Stream Format.
subroutine get_g2_fixedsurfacetypes (key, value, ierr)
This subroutine returns the corresponding GRIB2 - Fixed Surface Types and Units value for a given short key name based on Table 4.5 of Section 4, Octets 23 and 29.
subroutine get_g2_loctabversno (key, value, ierr)
This subroutine returns the corresponding GRIB2 local table version number for a given short key name based on Table 1.1.
subroutine get_g2_on388genproc (key, value, ierr)
This subroutine returns the corresponding GRIB1 - PDS Ocet6 data value (Generating process or model) from originating center 7 (USNWS NCEP) for a given short key name based on ON388 - Table A.
subroutine get_g2_on388origincenters (key, value, ierr)
This subroutine returns the corresponding GRIB1 - PDS Ocet5 GRIB2 - Section 1, Octet 6-7 National/International Originating Centers value for a given short key name based on ON388 - Table 0.
subroutine get_g2_ordofspcdiffvals (key, value, ierr)
This subroutine returns the corresponding GRIB2 - Table 5.6 Order of spatial differencing for a given short key name based on GRIB2 - Table 5.6 default is 1st order spatial differencing.
subroutine get_g2_prodstatus (key, value, ierr)
This subroutine returns the corresponding GRIB2 production status of data value for a given short key name based on Table 1.3.
subroutine get_g2_sec5packingmethod (key, value, ierr)
This subroutine returns the corresponding GRIB2 template number for a given short key name based on GRIB2 -.
subroutine get_g2_sigreftime (key, value, ierr)
This subroutine returns the corresponding GRIB2 significant reference time value for a given short key name based on Table 1.2.
subroutine get_g2_statprocesstypes (key, value, ierr)
This subroutine returns the corresponding GRIB2 - Type of statistica processing value for a given short key name based on Table 4.10 of Section 4 Octets 47 (template 8) 60 (temp 9), 48 (temp 10), 50 (temp 11), 49 (temp 12), 81 (temp 13), 77 (temp 14), 27 (temp 1001), 25 (temp 1002) and 39 (temp 1101)
subroutine get_g2_subcenters (key, value, ierr)
This subroutine returns the corresponding GRIB2 subcenters value for a given short key name based on Table C.
subroutine get_g2_typeofaerosol (key, value, ierr)
This subroutine returns the corresponding GRIB2 - Type of aerosol value for a given short key name based on Table 4.233 of Section 4 Octets 12-13 (template 44), 12-13 (temp 45), 12-13 (temp 46), 13-14 (temp 47), 12-13 (temp 48)
subroutine get_g2_typeofcluster (key, value, ierr)
This subroutine returns the corresponding GRIB2 type of clustering method for a given short key name based on Table 4.8.
subroutine get_g2_typeofcompression (key, value, ierr)
This subroutine returns the corresponding GRIB2 - Table 5.40 Type of compression for a given short key name based on GRIB2 - Table 5.40.
subroutine get_g2_typeofdata (key, value, ierr)
This subroutine returns the corresponding GRIB2 type of data value for a given short key name based on Table 1.4.
subroutine get_g2_typeofderivefcst (key, value, ierr)
This subroutine returns the corresponding GRIB2 type of derive forecast value for a given short key name based on Table 4.7.
subroutine get_g2_typeofensfcst (key, value, ierr)
This subroutine returns the corresponding GRIB2 type of ensemble forecast value for a given short key name based on Table 4.6.
subroutine get_g2_typeofgenproc (key, value, ierr)
This subroutine returns the corresponding GRIB2 - Type of Generating Process value for a given short key name based on Table 4.3 of Section 4, Octet 12.
subroutine get_g2_typeofintervals (key, value, ierr)
This subroutine returns the corresponding GRIB2 - Type of intervals value for a given short key name based on Table 4.91 of Section 4 Octets 14 (template 44) 14 (temp 45), 14 (temp 46), 15 (temp 47),14 and 25 (temp 48)
subroutine get_g2_typeoforigfieldvals (key, value, ierr)
This subroutine returns the corresponding GRIB2 - Table 5.1 Type of Original Field Values for a given short key name based on GRIB2 - Table 5.1.
subroutine get_g2_typeofprecip (key, value, ierr)
This subroutine returns the corresponding GRIB2 type of precipitation for a given short key name based on Table 4.201.
subroutine get_g2_typeofprob (key, value, ierr)
This subroutine returns the corresponding GRIB2 type of probability for a given short key name based on Table 4.9.
subroutine get_g2_typeoftimeintervals (key, value, ierr)
This subroutine returns the corresponding GRIB2 - Type of time intervals value for a given short key name based on Table 4.11 of Section 4 Octets 48 (template 8) 61 (temp 9), 49 (temp 10), 51 (temp 11), 50 (temp 12), 82 (temp 13), 78 (tem p 14), 28 (temp 1001), and 40 (temp 1101)
subroutine get_g2_unitoftimerange (key, value, ierr)
This subroutine returns the corresponding GRIB2 - Indicator of unit of time range value for a given short key name based on Table 4.4 of Section 4, Octet 18.
subroutine get_g2_versionno (key, value, ierr)
This subroutine returns the corresponding GRIB2 version number for a given short key name based on Table 1.0.
Variables
integer, parameter maxfixedsurfacetypes =200
Max fixed surface types.
integer, parameter maxgenproc =250
maxgenproc
integer, parameter maxlocver =20
maxlocver
integer, parameter maxordofsptdiff =50
maxordofsptdiff
integer, parameter maxorigincenters =500
maxorigincenters
integer, parameter maxprodstatus =17
maxprodstatus
integer, parameter maxreftime =15
maxreftime
integer, parameter maxstatprocesstypes =50
maxstatprocesstypes
integer, parameter maxsubcen =100
maxsubcen
integer, parameter maxtypeofaerosol =200
maxtypeofaerosol
integer, parameter maxtypeofcluster =100
maxtypeofcluster
integer, parameter maxtypeofcompression =50
maxtypeofcompression
integer, parameter maxtypeofdata =100
maxtypeofdata
integer, parameter maxtypeofderivefcst =100
maxtypeofderivefcst
integer, parameter maxtypeofensfcst =100
maxtypeofensfcst
integer, parameter maxtypeofgenproc =100
maxtypeofgenproc
integer, parameter maxtypeofintvls =50
maxtypeofintvls
integer, parameter maxtypeoforigfieldval =15
maxtypeoforigfieldval
integer, parameter maxtypeofpackingmethod =50
maxtypeofpackingmethod
integer, parameter maxtypeofprecip =100
maxtypeofprecip
integer, parameter maxtypeofprob =100
maxtypeofprob
integer, parameter maxtypeoftimeintvls =50
maxtypeoftimeintvls
integer, parameter maxunitoftimerange =30
maxunitoftimerange
integer, parameter maxver =100
maxver
type(origin_centers), dimension(maxorigincenters) on388_table0
ON388 Table.
type(gen_proc), dimension(maxgenproc) on388_tablea
ON 388 Table A.
type(version_no), dimension(maxver) table1_0
Table 1 0.
type(local_table_vers_no), dimension(maxlocver) table1_1
Table 1 1.
type(sigreftime), dimension(maxreftime) table1_2
Table 1 2.
type(prod_status), dimension(maxprodstatus) table1_3
Table 1 3.
type(type_of_data), dimension(maxtypeofdata) table1_4
table1_4
type(statistical_processing_types), dimension(maxstatprocesstypes) table4_10
table4_10
type(type_of_time_intervals), dimension(maxtypeoftimeintvls) table4_11
table4_11
type(type_of_precip), dimension(maxtypeofprecip) table4_201
table4_201
type(type_of_aerosol), dimension(maxtypeofaerosol) table4_233
table4_233
type(type_of_gen_proc), dimension(maxtypeofgenproc) table4_3
table4_3
type(unit_of_time_range), dimension(maxunitoftimerange) table4_4
table4_4
type(fixed_surface_types), dimension(maxfixedsurfacetypes) table4_5
table4_5
type(type_of_ens_fcst), dimension(maxtypeofensfcst) table4_6
table4_6
type(type_of_derive_fcst), dimension(maxtypeofderivefcst) table4_7
table4_7
type(type_of_cluster), dimension(maxtypeofcluster) table4_8
table4_8
type(type_of_prob), dimension(maxtypeofprob) table4_9
table4_9
type(type_of_intervals), dimension(maxtypeofintvls) table4_91
table4_91
type(type_of_packingmethod), dimension(maxtypeofpackingmethod) table5_0
table5_0
type(type_of_orig_field_vals), dimension(maxtypeoforigfieldval) table5_1
table5_1
type(type_of_compression), dimension(maxtypeofcompression) table5_40
table5_40
type(order_of_sptdiff_vals), dimension(maxordofsptdiff) table5_6
table5_6
type(subcenters), dimension(maxsubcen) tablec
tablec
Detailed Description
Define the variables in the derived data type discipline provided in Section 0.
Program History Log
Date Programmer Comments
12/04/2009 V. Krishna Kumar Creation
2012/01/25 Jun Wang Add template 4.44 and 4.48
2012/02/20 Jun Wang Add complex packing
2014/07/08 Boi Vuong Corrected Scaled value of second fixed surfaces in template 4.8 and Added generating process model HRRR
2015/01/09 Boi Vuong Added template 4.1, 411 and 4.12 and update code tables routines: get_g2_typeof ensfcst, get_g2_typeofderivefcst
2015/09/02 Boi Vuong Added 4 type of aerosols in table4_233
2017/03/01 Boi Vuong Added generating process model (HREF and Great lake short range model in table on388_tablea
2019/06/25 Boi Vuong Corrected tablec sub-center: Changed name: ncep_hpc to ncep_wpc; ncep_tpc to ncep_nhc; sec - swpc and aded new sub-center: esrl
2019/06/25 Boi Vuong 17 Added new entries in table4_3,table4_5 and added new table4_8,table4_9,table 4_201 Added generating process model table on388_tablea
2021/04/20 Boi Vuong Updated table 4.3, 4.5,4.7 and on388_tablea
Author
Jun Wang
Date
2012/01/25
Data Type Documentation
grib2_all_tables_module::fixed_surface_types
type grib2_all_tables_module::fixed_surface_types
Definition at line 293 of file grib2_all_tables_module.f90.
Data Fields
character(len=80) fixedsurfacetypeskey
integer fixedsurfacetypesval
grib2_all_tables_module::gen_proc
type grib2_all_tables_module::gen_proc
Definition at line 1044 of file grib2_all_tables_module.f90.
Data Fields
character(len=30) genprockey
integer genprocval
grib2_all_tables_module::local_table_vers_no
type grib2_all_tables_module::local_table_vers_no
Definition at line 144 of file grib2_all_tables_module.f90.
Data Fields
character(len=20) locverskey
integer locversval
grib2_all_tables_module::order_of_sptdiff_vals
type grib2_all_tables_module::order_of_sptdiff_vals
Definition at line 769 of file grib2_all_tables_module.f90.
Data Fields
character(len=50) ordofsptdiffkey
integer ordofsptdiffvals
grib2_all_tables_module::origin_centers
type grib2_all_tables_module::origin_centers
Definition at line 813 of file grib2_all_tables_module.f90.
Data Fields
character(len=50) origincenterskey
integer origincentersval
grib2_all_tables_module::prod_status
type grib2_all_tables_module::prod_status
Definition at line 178 of file grib2_all_tables_module.f90.
Data Fields
character(len=20) prodstatuskey
integer prodstatusval
grib2_all_tables_module::sigreftime
type grib2_all_tables_module::sigreftime
Definition at line 161 of file grib2_all_tables_module.f90.
Data Fields
character(len=20) sigrefkey
integer sigrefval
grib2_all_tables_module::statistical_processing_types
type grib2_all_tables_module::statistical_processing_types
Definition at line 501 of file grib2_all_tables_module.f90.
Data Fields
character(len=80) statprocesstypeskey
integer statprocesstypesval
grib2_all_tables_module::subcenters
type grib2_all_tables_module::subcenters
Definition at line 75 of file grib2_all_tables_module.f90.
Data Fields
character(len=20) subcenkey
integer subcenval
grib2_all_tables_module::type_of_aerosol
type grib2_all_tables_module::type_of_aerosol
Definition at line 611 of file grib2_all_tables_module.f90.
Data Fields
character(len=80) typeofaerosolkey
integer typeofaerosolval
grib2_all_tables_module::type_of_cluster
type grib2_all_tables_module::type_of_cluster
Definition at line 468 of file grib2_all_tables_module.f90.
Data Fields
character(len=80) typeofclusterkey
integer typeofclusterval
grib2_all_tables_module::type_of_compression
type grib2_all_tables_module::type_of_compression
Definition at line 781 of file grib2_all_tables_module.f90.
Data Fields
character(len=50) typeofcompressionkey
integer typeofcompressionvals
grib2_all_tables_module::type_of_data
type grib2_all_tables_module::type_of_data
Definition at line 201 of file grib2_all_tables_module.f90.
Data Fields
character(len=20) typeofdatakey
integer typeofdataval
grib2_all_tables_module::type_of_derive_fcst
type grib2_all_tables_module::type_of_derive_fcst
Definition at line 430 of file grib2_all_tables_module.f90.
Data Fields
character(len=50) typeofderivefcstkey
integer typeofderivefcstval
grib2_all_tables_module::type_of_ens_fcst
type grib2_all_tables_module::type_of_ens_fcst
Definition at line 414 of file grib2_all_tables_module.f90.
Data Fields
character(len=50) typeofensfcstkey
integer typeofensfcstval
grib2_all_tables_module::type_of_gen_proc
type grib2_all_tables_module::type_of_gen_proc
Definition at line 222 of file grib2_all_tables_module.f90.
Data Fields
character(len=30) typeofgenprockey
integer typeofgenprocval
grib2_all_tables_module::type_of_intervals
type grib2_all_tables_module::type_of_intervals
Definition at line 564 of file grib2_all_tables_module.f90.
Data Fields
character(len=80) typeofintervalskey
integer typeofintervalsval
grib2_all_tables_module::type_of_orig_field_vals
type grib2_all_tables_module::type_of_orig_field_vals
Definition at line 747 of file grib2_all_tables_module.f90.
Data Fields
integer typeoforigfieldvals
character(len=50) typeoforigfieldvalskey
grib2_all_tables_module::type_of_packingmethod
type grib2_all_tables_module::type_of_packingmethod
Definition at line 793 of file grib2_all_tables_module.f90.
Data Fields
character(len=50) packingmethodkey
integer packingmethodvals
grib2_all_tables_module::type_of_precip
type grib2_all_tables_module::type_of_precip
Definition at line 588 of file grib2_all_tables_module.f90.
Data Fields
character(len=80) typeofprecipkey
integer typeofprecipval
grib2_all_tables_module::type_of_prob
type grib2_all_tables_module::type_of_prob
Definition at line 482 of file grib2_all_tables_module.f90.
Data Fields
character(len=80) typeofprobkey
integer typeofprobval
grib2_all_tables_module::type_of_time_intervals
type grib2_all_tables_module::type_of_time_intervals
Definition at line 544 of file grib2_all_tables_module.f90.
Data Fields
character(len=80) typeoftimeintervalskey
integer typeoftimeintervalsval
grib2_all_tables_module::unit_of_time_range
type grib2_all_tables_module::unit_of_time_range
Definition at line 270 of file grib2_all_tables_module.f90.
Data Fields
character(len=30) unitoftimerangekey
integer unitoftimerangeval
grib2_all_tables_module::version_no
type grib2_all_tables_module::version_no
Definition at line 104 of file grib2_all_tables_module.f90.
Data Fields
character(len=20) verskey
integer versval
Function/Subroutine Documentation
g2sec0()
subroutine grib2_all_tables_module::g2sec0 (integer idisc, integer, dimension(2) listsec0)
This subroutine returns the section 0 list for a given discipline value.
Parameters
[in] idisc - GRIB2 Discipline (From Table 0.0)
[out] listsec0 - Section 0
listsec0(1) - GRIB2 Discipline (From Table 0.0)
listsec0(2) - Edition number - 2 for GRIB2
Author
V. Krishna Kumar ORG: W/NP12
Date
2010-03-01
Definition at line 1680 of file grib2_all_tables_module.f90.
g2sec1()
subroutine grib2_all_tables_module::g2sec1 (character(len=*) origin_key, character(len=*) subcen_key, character(len=*) vers_key, character(len=*) lvers_key, character(len=*) sigreftime_key, integer refyear_val, integer refmon_val, integer refday_val, integer refhour_val, integer refmin_val, integer refsec_val, character(len=*) prodstatus_key, character(len=*) typeofdata_key, integer, dimension(13) listsec1)
This subroutine returns the section 1 list for given keys.
Parameters
[in] origin_key - Identification of originating/generating center (See Table 0 {GRIB1})
[in] subcen_key - Identification of originating/generating subcenter (See Table C)
[in] vers_key - GRIB master tables version number (currently 2) (See Table 1.0) (See note 1 below)
[in] lvers_key - Version number of GRIB local tables used to augment Master Tables (see Table 1.1)
[in] sigreftime_key - Significance of reference time (See Table 1.2)
[in] refyear_val - Year (4 digits)
[in] refmon_val - Month
[in] refday_val - Day
[in] refhour_val - Hour
[in] refmin_val - Minute
[in] refsec_val - Second
[in] prodstatus_key - Production Status of Processed data in the GRIB message (See Table 1.3)
[in] typeofdata_key - Type of processed data in this GRIB message (See Table 1.4)
[out] listsec1 - GRIB2 Section 1 Identification Section values array
Author
V. Krishna Kumar ORG: W/NP12
Date
2010-03-01
Definition at line 1706 of file grib2_all_tables_module.f90.
References get_g2_loctabversno(), get_g2_on388origincenters(), get_g2_prodstatus(), get_g2_sigreftime(), get_g2_subcenters(), get_g2_typeofdata(), and get_g2_versionno().
g2sec4_temp0()
subroutine grib2_all_tables_module::g2sec4_temp0 (integer(4), intent(in) icatg, integer(4), intent(in) iparm, character(len=*), intent(in) typ_gen_proc_key, character(len=*), intent(in) gen_proc_or_mod_key, integer(4), intent(in) hrs_obs_cutoff, integer(4), intent(in) min_obs_cutoff, character(len=*), intent(in) unit_of_time_key, integer(4), intent(in) fcst_time, character(len=*), intent(in) lvl_type1, integer(4), intent(in) scale_fac1, integer(4), intent(in) scaled_val1, character(len=*), intent(in) lvl_type2, integer(4), intent(in) scale_fac2, integer(4), intent(in) scaled_val2, integer(4), dimension(15), intent(inout) ipdstmpl0)
This subroutine returns the Grib2 Section 4 Template 4.0 list for given keys PDT 4.0 - Analysis or forecast at a horizontal level or in a horizontal layer at a point in time.
Parameters
[in] icatg - Parameter category (see Code table 4.1)
[in] iparm - Parameter number (see Code table 4.2)
[in] typ_gen_proc_key - Type of generating process (see Code table 4.3)
[in] gen_proc_or_mod_key - Analysis or forecast generating process identified (see Code ON388 Table A)
[in] hrs_obs_cutoff - Hours of observational data cutoff after reference time (see Note)
[in] min_obs_cutoff - Minutes of observational data cutoff after reference time (see Note)
[in] unit_of_time_key - Indicator of unit of time range (see Code table 4.4)
[in] fcst_time - Forecast time in units defined by octet 18
[in] lvl_type1 - Type of first fixed surface (see Code table 4.5)
[in] scale_fac1 - Scale factor of first fixed surface
[in] scaled_val1 - Scaled value of first fixed surface
[in] lvl_type2 - Type of second fixed surfaced (see Code table 4.5)
[in] scale_fac2 - Scale factor of second fixed surface
[in] scaled_val2 - Scaled value of second fixed surfaces
[out] ipdstmpl0 - GRIB2 PDS Template 4.0 listing
Author
V. Krishna Kumar ORG: W/NP12
Date
2010-03-01
Definition at line 1770 of file grib2_all_tables_module.f90.
References get_g2_fixedsurfacetypes(), get_g2_on388genproc(), get_g2_typeofgenproc(), and get_g2_unitoftimerange().
g2sec4_temp44()
subroutine grib2_all_tables_module::g2sec4_temp44 (integer(4), intent(in) icatg, integer(4), intent(in) iparm, character(len=*), intent(in) aer_type, character(len=*), intent(in) typ_intvl_size, integer(4), intent(in) scale_fac1_size, real, intent(in) scale_val1_size, integer(4), intent(in) scale_fac2_size, real, intent(in) scale_val2_size, character(len=*), intent(in) typ_gen_proc_key, character(len=*), intent(in) gen_proc_or_mod_key, integer(4), intent(in) hrs_obs_cutoff, integer(4), intent(in) min_obs_cutoff, character(len=*), intent(in) unit_of_time_key, integer(4), intent(in) fcst_time, character(len=*), intent(in) lvl_type1, integer(4), intent(in) scale_fac1, integer(4), intent(in) scaled_val1, character(len=*), intent(in) lvl_type2, integer(4), intent(in) scale_fac2, integer(4), intent(in) scaled_val2, integer(4), dimension(21), intent(inout) ipdstmpl44)
This subroutine returns the Grib2 Section 4 Template 4.44 list for given keys PDT 4.44 - Analysis or forecast at a horizontal level or in a horizontal layer at a point in time for aerosol.
Parameters
[in] icatg - Parameter category (see Code table 4.1)
[in] iparm - Parameter number (see Code table 4.2)
[in] aer_type - Aetosol type (see Code table 4.233)
[in] typ_intvl_size - Type of interval for first and second size (see Code table 4.91)
[in] scale_fac1_size - Scale factor of first size
[in] scale_val1_size - Scale value of first size in meters
[in] scale_fac2_size - Scale factor of second size
[in] scale_val2_size - Scale value of second size in meters
[in] typ_gen_proc_key - Type of generating process (see Code table 4.3)
[in] gen_proc_or_mod_key - Analysis or forecast generating process identified (see Code ON388 Table A)
[in] hrs_obs_cutoff - Hours of observational data cutoff after reference time (see Note)
[in] min_obs_cutoff - Minutes of observational data cutoff after reference time (see Note)
[in] unit_of_time_key - Indicator of unit of time range (see Code table 4.4)
[in] fcst_time - Forecast time in units defined by octet 18
[in] lvl_type1 - Type of first fixed surface (see Code table 4.5)
[in] scale_fac1 - Scale factor of first fixed surface
[in] scaled_val1 - Scaled value of first fixed surface
[in] lvl_type2 - Type of second fixed surfaced (see Code table 4.5)
[in] scale_fac2 - Scale factor of second fixed surface
[in] scaled_val2 - Scaled value of second fixed surfaces
[out] ipdstmpl44 - GRIB2 PDS Template 4.44 listing
Author
J. WANG ORG: NCEP/EMC
Date
2012-01-25
Definition at line 1989 of file grib2_all_tables_module.f90.
References get_g2_fixedsurfacetypes(), get_g2_on388genproc(), get_g2_typeofaerosol(), get_g2_typeofgenproc(), get_g2_typeofintervals(), and get_g2_unitoftimerange().
g2sec4_temp48()
subroutine grib2_all_tables_module::g2sec4_temp48 (integer(4), intent(in) icatg, integer(4), intent(in) iparm, character(len=*), intent(in) aer_type, character(len=*), intent(in) typ_intvl_size, integer(4), intent(in) scale_fac1_size, real, intent(in) scale_val1_size, integer(4), intent(in) scale_fac2_size, real, intent(in) scale_val2_size, character(len=*), intent(in) typ_intvl_wavelength, integer(4), intent(in) scale_fac1_wavelength, real, intent(in) scale_val1_wavelength, integer(4), intent(in) scale_fac2_wavelength, real, intent(in) scale_val2_wavelength, character(len=*), intent(in) typ_gen_proc_key, character(len=*), intent(in) gen_proc_or_mod_key, integer(4), intent(in) hrs_obs_cutoff, integer(4), intent(in) min_obs_cutoff, character(len=*), intent(in) unit_of_time_key, integer(4), intent(in) fcst_time, character(len=*), intent(in) lvl_type1, integer(4), intent(in) scale_fac1, integer(4), intent(in) scaled_val1, character(len=*), intent(in) lvl_type2, integer(4), intent(in) scale_fac2, integer(4), intent(in) scaled_val2, integer(4), dimension(26), intent(inout) ipdstmpl48)
This subroutine returns the Grib2 Section 4 Template 4.0 list for given keys PDT 4.48 - Analysis or forecast at a horizontal level or in a horizontal layer at a point in time for aerosol.
Parameters
[in] icatg - Parameter category (see Code table 4.1)
[in] iparm - Parameter number (see Code table 4.2)
[in] aer_type - Aetosol type (see Code table 4.233)
[in] typ_intvl_size - Type of interval for first and second size (see Code table 4.91)
[in] scale_fac1_size - Scale factor of first size
[in] scale_val1_size - Scale value of first size in meters
[in] scale_fac2_size - Scale factor of second size
[in] scale_val2_size - Scale value of second size in meters
[in] typ_intvl_wavelength - Type of interval for first and second wavelength (see Code table 4.91)
[in] scale_fac1_wavelength - Scale factor of first wavelength
[in] scale_val1_wavelength - Scale value of first wavelength in meters
[in] scale_fac2_wavelength - Scale factor of second wavelength
[in] scale_val2_wavelength - Scale value of second wavelength in meters
[in] typ_gen_proc_key - Type of generating process (see Code table 4.3)
[in] gen_proc_or_mod_key - Analysis or forecast generating process identified (see Code ON388 Table A)
[in] hrs_obs_cutoff - Hours of observational data cutoff after reference time (see Note)
[in] min_obs_cutoff - Minutes of observational data cutoff after reference time (see Note)
[in] unit_of_time_key - Indicator of unit of time range (see Code table 4.4)
[in] fcst_time - Forecast time in units defined by octet 18
[in] lvl_type1 - Type of first fixed surface (see Code table 4.5)
[in] scale_fac1 - Scale factor of first fixed surface
[in] scaled_val1 - Scaled value of first fixed surface
[in] lvl_type2 - Type of second fixed surfaced (see Code table 4.5)
[in] scale_fac2 - Scale factor of second fixed surface
[in] scaled_val2 - Scaled value of second fixed surfaces
[out] ipdstmpl48 - GRIB2 PDS Template 4.48 listing
Author
J. WANG ORG: NCEP/EMC
Date
2012-01-25
Definition at line 2085 of file grib2_all_tables_module.f90.
References get_g2_fixedsurfacetypes(), get_g2_on388genproc(), get_g2_typeofaerosol(), get_g2_typeofgenproc(), get_g2_typeofintervals(), and get_g2_unitoftimerange().
g2sec4_temp8()
subroutine grib2_all_tables_module::g2sec4_temp8 (integer(4), intent(in) icatg, integer(4), intent(in) iparm, character(len=*), intent(in) typ_gen_proc_key, character(len=*), intent(in) gen_proc_or_mod_key, integer(4), intent(in) hrs_obs_cutoff, integer(4), intent(in) min_obs_cutoff, character(len=*), intent(in) unit_of_time_key, integer(4), intent(in) fcst_time, character(len=*), intent(in) lvl_type1, integer(4), intent(in) scale_fac1, integer(4), intent(in) scaled_val1, character(len=*), intent(in) lvl_type2, integer(4), intent(in) scale_fac2, integer(4), intent(in) scaled_val2, integer(4), intent(in) year_intvl, integer(4), intent(in) mon_intvl, integer(4), intent(in) day_intvl, integer(4), intent(in) hour_intvl, integer(4), intent(in) min_intvl, integer(4), intent(in) sec_intvl, integer(4), intent(in) num_time_range, integer(4), intent(in) stat_miss_val, character(len=*), intent(in) type_of_stat_proc, character(len=*), intent(in) type_of_time_inc, character(len=*), intent(in) stat_unit_time_key, integer(4), intent(in) leng_time_range_stat, character(len=*), intent(in) stat_unit_time_key_succ, integer(4), intent(in) time_inc_betwn_succ_fld, integer(4), dimension(29), intent(inout) ipdstmpl8)
This subroutine returns the Grib2 Section 4 Template 4.8 list for given keys PDT 4.8 - Average, accumulation, extreme values or other statistically processed values at a horizontal level or in a horizontal layer in a continuous or non-continuous time interval.
PROGRAM HISTORY LOG: 2010-03-01 V. Krishna Kumar 2010-04-20 Jun Wang
Parameters
[in] icatg - Parameter category (see Code Table 4.1)
[in] iparm - Parameter number (see Code Table 4.2)
[in] typ_gen_proc_key - Type of generating process (see Code Table 4.3)
[in] gen_proc_or_mod_key - Analysis or forecast generating process identified (see Code ON388 Table A)
[in] hrs_obs_cutoff - Hours after reference time data cutoff (see Note 1)
[in] min_obs_cutoff - Minutes after reference time data cutoff
[in] unit_of_time_key - Indicator of unit of time range (see Code Table 4.4)
[in] fcst_time - Forecast time in units defined by octet 18 (see Note 2)
[in] lvl_type1 - Type of first fixed surface (see Code Table 4.5)
[in] scale_fac1 - Scale factor of first fixed surface
[in] scaled_val1 - Scaled value of first fixed surface
[in] lvl_type2 - Type of second fixed surfaced (see Code Table 4.5)
[in] scale_fac2 - Scale factor of second fixed surface
[in] scaled_val2 - Scaled value of second fixed surfaces
[in] year_intvl - Year Time of end of overall time interval
[in] mon_intvl - Month Time of end of overall time interval
[in] day_intvl - Day Time of end of overall time interval
[in] hour_intvl - Hour Time of end of overall time interval
[in] min_intvl - Minute Time of end of overall time interval
[in] sec_intvl - Second Time of end of overall time interval
[in] num_time_range - n number of time ranges specifications describing the time intervals used to calculate the statistically-processed field
[in] stat_miss_val - Total number of data values missing in statistical process Specification of the outermost (or only) time range over which statistical processing is done
[in] type_of_stat_proc - Statistical process used to calculate the processed field from the field at each time increment during the time range (see Code Table 4.10)
[in] type_of_time_inc - Type of time increment between successive fields used in the statistical processing (see Code Table 4.11)
[in] stat_unit_time_key - Indicator of unit of time for time range over which statistical processing is done (see Code Table 4.4)
[in] leng_time_range_stat - Length of the time range over which statistical processing is done, in units defined by the previous octet
[in] stat_unit_time_key_succ - Indicator of unit of time for the increment between the successive fields used (see Code table 4.4)
[in] time_inc_betwn_succ_fld - Time increment between successive fields, in units defined by the previous octet (see Notes 3 & 4)
[out] ipdstmpl8 - GRIB2 PDS Template 4.8 listing
Author
V. Krishna Kumar ORG: W/NP12
Date
2010-03-01
Definition at line 1872 of file grib2_all_tables_module.f90.
References get_g2_fixedsurfacetypes(), get_g2_on388genproc(), get_g2_statprocesstypes(), get_g2_typeofgenproc(), get_g2_typeoftimeintervals(), and get_g2_unitoftimerange().
g2sec5_temp0()
subroutine grib2_all_tables_module::g2sec5_temp0 (integer(4), intent(in) dec_scale_fac, integer(4), intent(in) bin_scale_fac, integer(4), intent(in) tlnumbits, integer(4), dimension(5), intent(out) ifield5)
This subroutine returns the section 5 list array for a given decimal scale factor (D) and type of original field values (Table 5.1) value from GRIB2 - GRID Template 5.0 Grid point data - simple packing.
PROGRAM HISTORY LOG: 2010-03-01 V. Krishna Kumar 2012-02-21 J. Wang add binary scale factor and number of bits in argument list
Parameters
[in] dec_scale_fac - Decimal scale factor (E)
[in] bin_scale_fac - binary scale factor (D)
[in] tlnumbits - Number of bits used
[out] ifield5 - GRIB2 - GRID Template 5.0 listing
ifield5(1): reference value(R) (IEEE 32-bit floating-point value)
ifield5(2): binary scale factor (E)
ifield5(3): decimal scale factor (D)
ifield5(4): number of bits used for each packed value for simple packing or for each group reference value for complex packing or spatial differencing
ifield5(5): type of original field values (See Code Table 5.1)
Author
V. Krishna Kumar ORG: W/NP12
Date
2010-03-01
Definition at line 2233 of file grib2_all_tables_module.f90.
g2sec5_temp2()
subroutine grib2_all_tables_module::g2sec5_temp2 (integer(4), intent(in) dec_scale_fac, integer(4), intent(in) bin_scale_fac, integer(4), dimension(16), intent(inout) ifield5)
This subroutine returns the section 5 list array with a given binary, and decimal scale factor from GRIB2 - GRID Template 5.2 Grid point data - complex packing.
Parameters
[in] bin_scale_fac - binary scale factor (E)
[in] dec_scale_fac - Decimal scale factor (D)
[out] ifield5 - GRIB2 - GRID Template 5.2 listing
ifield5(1): reference value(R) (IEEE 32-bit floating-point value)
ifield5(2): binary scale factor (E)
ifield5(3): decimal scale factor (D)
ifield5(4): number of bits used for each packed value for simple packing or for each group reference value for complex packing or spatial differencing
Author
J.Wang ORG: W/EMC
Date
2012-02-20
Definition at line 2262 of file grib2_all_tables_module.f90.
g2sec5_temp3()
subroutine grib2_all_tables_module::g2sec5_temp3 (integer(4), intent(in) dec_scale_fac, integer(4), intent(in) bin_scale_fac, character(*), intent(in) order_of_sptdiff, integer(4), dimension(18), intent(out) ifield5)
This subroutine returns the section 5 list array with a given binary, and decimal scale factor from GRIB2 - GRID Template 5.3 Grid point data - complex packing with spatial difference.
Parameters
[in] bin_scale_fac - binary scale factor (E)
[in] dec_scale_fac - Decimal scale factor (D)
[in] order_of_sptdiff - Order of spatial difference
[out] ifield5 - GRIB2 - GRID Template 5.3 listing
ifield5(1): reference value(R) (IEEE 32-bit floating-point value)
ifield5(2): binary scale factor (E)
ifield5(3): decimal scale factor (D)
ifield5(4): number of bits used for each packed value for simple packing or for each group reference value for complex packing or spatial differencing
Author
J.Wang ORG: W/EMC
Date
2012-02-20
Definition at line 2292 of file grib2_all_tables_module.f90.
References get_g2_ordofspcdiffvals().
g2sec5_temp40()
subroutine grib2_all_tables_module::g2sec5_temp40 (integer(4), intent(in) dec_scale_fac, integer(4), intent(in) bin_scale_fac, integer(4), intent(in) tlnumbits, character(*), intent(in) type_of_compression, integer(4), dimension(7), intent(inout) ifield5)
This subroutine returns the section 5 list array for a given decimal scale factor (D),type of original field value (Table 5.40) and type of compression used from GRIB2 - GRID Template 5.40 Grid point data - JPEG 2000 Code Stream Format.
PROGRAM HISTORY LOG: 2010-03-01 V. Krishna Kumar 2010-04-07 Jun Wang add total number of bits
Parameters
[in] dec_scale_fac - Decimal scale factor (D)
[in] bin_scale_fac - binary scale factor (B)
[in] tlnumbits - total number of bits
[in] type_of_compression - Type of original field values (see Code Table 5.40)
[out] ifield5 - GRIB2 - GRID Template 5.40 listing
ifield5(1): reference value(R) (IEEE 32-bit floating-point value)
ifield5(2): binary scale factor (E)
ifield5(3): decimal scale factor (D)
ifield5(4): number of bits required to hold the resulting scaled and reference data values (i.e. The depth of the grayscale image.) (see Note 2)
ifield5(5): type of original field values (See Code Table 5.1)
ifield5(6): type of compression used (See Code Table 5.40)
ifield5(7): target compression ration, M:1 (with respect to the bit-depth specified in octet 20), when octet 22 indicates Lossy Compression. Otherwise, set to missing (see Note 3)
Author
V. Krishna Kumar ORG: W/NP12
Date
2010-03-01
Definition at line 2337 of file grib2_all_tables_module.f90.
References get_g2_typeofcompression().
get_g2_fixedsurfacetypes()
subroutine grib2_all_tables_module::get_g2_fixedsurfacetypes (character(len=*) key, integer value, integer ierr)
This subroutine returns the corresponding GRIB2 - Fixed Surface Types and Units value for a given short key name based on Table 4.5 of Section 4, Octets 23 and 29.
Parameters
[in] key - GRIB2 character short key for fixed surface types from Table 4.5
[out] value - corresponding GRIB2 value from Table 4.5
[out] ierr - error messages
Author
V. Krishna Kumar ORG: W/NP12
Date
2009-12-10
Definition at line 1384 of file grib2_all_tables_module.f90.
References maxfixedsurfacetypes, and table4_5.
Referenced by g2sec4_temp0(), g2sec4_temp1(), g2sec4_temp11(), g2sec4_temp12(), g2sec4_temp44(), g2sec4_temp48(), and g2sec4_temp8().
get_g2_loctabversno()
subroutine grib2_all_tables_module::get_g2_loctabversno (character(len=*) key, integer value, integer ierr)
This subroutine returns the corresponding GRIB2 local table version number for a given short key name based on Table 1.1.
Parameters
[in] key - GRIB2 character short key for local table version number
[out] value - corresponding GRIB2 local table version number value from table 1.1
[out] ierr - error messages
Author
V. Krishna Kumar ORG: W/NP12
Date
2009-12-10
Definition at line 1237 of file grib2_all_tables_module.f90.
References maxlocver, and table1_1.
Referenced by g2sec1().
get_g2_on388genproc()
subroutine grib2_all_tables_module::get_g2_on388genproc (character(len=*) key, integer value, integer ierr)
This subroutine returns the corresponding GRIB1 - PDS Ocet6 data value (Generating process or model) from originating center 7 (USNWS NCEP) for a given short key name based on ON388 - Table A.
Parameters
[in] key - GRIB1 character short key for model based on ON388 - Table A
[out] value - corresponding GRIB1 - PDS Octet 6 value from ON388 - Table A
[out] ierr - error messages
Author
V. Krishna Kumar ORG: W/NP12
Date
2009-12-10
Definition at line 1552 of file grib2_all_tables_module.f90.
References maxgenproc, and on388_tablea.
Referenced by g2sec4_temp0(), g2sec4_temp1(), g2sec4_temp11(), g2sec4_temp12(), g2sec4_temp44(), g2sec4_temp48(), and g2sec4_temp8().
get_g2_on388origincenters()
subroutine grib2_all_tables_module::get_g2_on388origincenters (character(len=*) key, integer value, integer ierr)
This subroutine returns the corresponding GRIB1 - PDS Ocet5 GRIB2 - Section 1, Octet 6-7 National/International Originating Centers value for a given short key name based on ON388 - Table 0.
Parameters
[in] key - GRIB1 character short key for originating center based on ON388 - Table 0
[out] value - corresponding GRIB1-PDS Octet 5/GRIB2-Section 1, Octets 6-7 value from ON388 - Table 0
[out] ierr - error messages
Author
V. Krishna Kumar ORG: W/NP12
Date
2009-12-10
Definition at line 1527 of file grib2_all_tables_module.f90.
References maxorigincenters, and on388_table0.
Referenced by g2sec1().
get_g2_ordofspcdiffvals()
subroutine grib2_all_tables_module::get_g2_ordofspcdiffvals (character(len=*) key, integer value, integer ierr)
This subroutine returns the corresponding GRIB2 - Table 5.6 Order of spatial differencing for a given short key name based on GRIB2 - Table 5.6 default is 1st order spatial differencing.
Parameters
[in] key - GRIB2 character short key for Order of spatial differencing based on Table 5.6
[out] value - corresponding GRIB2 - Table 5.6 value
[out] ierr - error messages
Author
J.Wang ORG: NCEP/EMC
Date
2012-02-20
Definition at line 1602 of file grib2_all_tables_module.f90.
References maxordofsptdiff, and table5_6.
Referenced by g2sec5_temp3().
get_g2_prodstatus()
subroutine grib2_all_tables_module::get_g2_prodstatus (character(len=*) key, integer value, integer ierr)
This subroutine returns the corresponding GRIB2 production status of data value for a given short key name based on Table 1.3.
Parameters
[in] key - GRIB2 character short key for production status of data
[out] value - corresponding GRIB2 significant value from table 1.3
[out] ierr - error messages
Author
V. Krishna Kumar ORG: W/NP12
Date
2009-12-10
Definition at line 1286 of file grib2_all_tables_module.f90.
References maxprodstatus, and table1_3.
Referenced by g2sec1().
get_g2_sec5packingmethod()
subroutine grib2_all_tables_module::get_g2_sec5packingmethod (character(len=*) key, integer value, integer ierr)
This subroutine returns the corresponding GRIB2 template number for a given short key name based on GRIB2 -.
PROGRAM HISTORY LOG: 2009-12-10 V. Krishna Kumar 2010-03-15 Jun Wang : get section5 template number
Parameters
[in] key - GRIB2 character short key for packing method based on Table 5.0
[out] value - corresponding GRIB2 - Table 5.0 value
[out] ierr - error messages
Author
V. Krishna Kumar ORG: W/NP12
Date
2010-03-08
Definition at line 1655 of file grib2_all_tables_module.f90.
References maxtypeofpackingmethod, and table5_0.
get_g2_sigreftime()
subroutine grib2_all_tables_module::get_g2_sigreftime (character(len=*) key, integer value, integer ierr)
This subroutine returns the corresponding GRIB2 significant reference time value for a given short key name based on Table 1.2.
Parameters
[in] key - GRIB2 character short key for significant reference time
[out] value - corresponding GRIB2 significant value from table 1.2
[out] ierr - error messages
Author
V. Krishna Kumar ORG: W/NP12
Date
2009-12-10
Definition at line 1261 of file grib2_all_tables_module.f90.
References maxreftime, and table1_2.
Referenced by g2sec1().
get_g2_statprocesstypes()
subroutine grib2_all_tables_module::get_g2_statprocesstypes (character(len=*), intent(in) key, integer value, integer ierr)
This subroutine returns the corresponding GRIB2 - Type of statistica processing value for a given short key name based on Table 4.10 of Section 4 Octets 47 (template 8) 60 (temp 9), 48 (temp 10), 50 (temp 11), 49 (temp 12), 81 (temp 13), 77 (temp 14), 27 (temp 1001), 25 (temp 1002) and 39 (temp 1101)
Parameters
[in] key - GRIB2 character short key for type of statistical processing from Table 4.10
[out] value - corresponding GRIB2 value from Table 4.10
[out] ierr - error messages
Author
V. Krishna Kumar ORG: W/NP12
Date
2009-12-10
Definition at line 1413 of file grib2_all_tables_module.f90.
References maxstatprocesstypes, and table4_10.
Referenced by g2sec4_temp11(), g2sec4_temp12(), and g2sec4_temp8().
get_g2_subcenters()
subroutine grib2_all_tables_module::get_g2_subcenters (character(len=*) key, integer value, integer ierr)
This subroutine returns the corresponding GRIB2 subcenters value for a given short key name based on Table C.
Parameters
[in] key - GRIB2 character short key for subcenter
[out] value - corresponding GRIB2 subcenter value from table c
[out] ierr - Error return code.
0 = no error
9 = key not found
Author
V. Krishna Kumar ORG: W/NP12
Date
2009-12-10
Definition at line 1189 of file grib2_all_tables_module.f90.
References maxsubcen, and tablec.
Referenced by g2sec1().
get_g2_typeofaerosol()
subroutine grib2_all_tables_module::get_g2_typeofaerosol (character(len=*) key, integer value, integer ierr)
This subroutine returns the corresponding GRIB2 - Type of aerosol value for a given short key name based on Table 4.233 of Section 4 Octets 12-13 (template 44), 12-13 (temp 45), 12-13 (temp 46), 13-14 (temp 47), 12-13 (temp 48)
Parameters
[in] key - GRIB2 character short key for type of aerosol from Table 4.233
[out] value - corresponding GRIB2 value from Table 4.233
[out] ierr - error messages
Author
V. Krishna Kumar ORG: W/NP12
Date
2010-04-03
Definition at line 1497 of file grib2_all_tables_module.f90.
References maxtypeofaerosol, and table4_233.
Referenced by g2sec4_temp44(), and g2sec4_temp48().
get_g2_typeofcluster()
subroutine grib2_all_tables_module::get_g2_typeofcluster (character(len=*) key, integer value, integer ierr)
This subroutine returns the corresponding GRIB2 type of clustering method for a given short key name based on Table 4.8.
Parameters
[in] key - GRIB2 character short key for type of clustering method
[out] value - corresponding GRIB2 type of cluster value from table 4.8
[out] ierr - error messages
Author
Boi Vuong ORG: EMC/EIB
Date
2019-07-01
Definition at line 2373 of file grib2_all_tables_module.f90.
References maxtypeofcluster, and table4_8.
get_g2_typeofcompression()
subroutine grib2_all_tables_module::get_g2_typeofcompression (character(len=*) key, integer value, integer ierr)
This subroutine returns the corresponding GRIB2 - Table 5.40 Type of compression for a given short key name based on GRIB2 - Table 5.40.
Parameters
[in] key - GRIB2 character short key for type of compression based on Table 5.40
[out] value - corresponding GRIB2 - Table 5.40 value
[out] ierr - error messages
Author
V. Krishna Kumar ORG: W/NP12
Date
2010-03-08
Definition at line 1627 of file grib2_all_tables_module.f90.
References maxtypeofcompression, and table5_40.
Referenced by g2sec5_temp40().
get_g2_typeofdata()
subroutine grib2_all_tables_module::get_g2_typeofdata (character(len=*) key, integer value, integer ierr)
This subroutine returns the corresponding GRIB2 type of data value for a given short key name based on Table 1.4.
Parameters
[in] key - GRIB2 character short key for production status of data
[out] value - corresponding GRIB2 type of data value from table 1.4
[out] ierr - error messages
Author
V. Krishna Kumar ORG: W/NP12
Date
2009-12-10
Definition at line 1310 of file grib2_all_tables_module.f90.
References maxtypeofdata, and table1_4.
Referenced by g2sec1().
get_g2_typeofderivefcst()
subroutine grib2_all_tables_module::get_g2_typeofderivefcst (character(len=*) key, integer value, integer ierr)
This subroutine returns the corresponding GRIB2 type of derive forecast value for a given short key name based on Table 4.7.
Parameters
[in] key - GRIB2 character short key for type of derive forecast
[out] value - corresponding GRIB2 type of derive forecast value from table 4.7
[out] ierr - error messages
Author
Boi Vuong ORG: W/SIB
Date
2015-01-09
Definition at line 2196 of file grib2_all_tables_module.f90.
References maxtypeofderivefcst, and table4_7.
Referenced by g2sec4_temp12().
get_g2_typeofensfcst()
subroutine grib2_all_tables_module::get_g2_typeofensfcst (character(len=*) key, integer value, integer ierr)
This subroutine returns the corresponding GRIB2 type of ensemble forecast value for a given short key name based on Table 4.6.
Parameters
[in] key - GRIB2 character short key for type of ensemble forecast
[out] value - corresponding GRIB2 type of ensemble forecast value from table 4.6
[out] ierr - error messages
Author
Boi Vuong ORG: W/SIB
Date
2015-01-09
Definition at line 2172 of file grib2_all_tables_module.f90.
References maxtypeofensfcst, and table4_6.
Referenced by g2sec4_temp1(), and g2sec4_temp11().
get_g2_typeofgenproc()
subroutine grib2_all_tables_module::get_g2_typeofgenproc (character(len=*) key, integer value, integer ierr)
This subroutine returns the corresponding GRIB2 - Type of Generating Process value for a given short key name based on Table 4.3 of Section 4, Octet 12.
Parameters
[in] key - GRIB2 character short key for type of generating process from Table 4.3
[out] value - corresponding GRIB2 value from Table 4.3
[out] ierr - error messages
Author
V. Krishna Kumar ORG: W/NP12
Date
2009-12-10
Definition at line 1334 of file grib2_all_tables_module.f90.
References maxtypeofgenproc, and table4_3.
Referenced by g2sec4_temp0(), g2sec4_temp1(), g2sec4_temp11(), g2sec4_temp12(), g2sec4_temp44(), g2sec4_temp48(), and g2sec4_temp8().
get_g2_typeofintervals()
subroutine grib2_all_tables_module::get_g2_typeofintervals (character(len=*) key, integer value, integer ierr)
This subroutine returns the corresponding GRIB2 - Type of intervals value for a given short key name based on Table 4.91 of Section 4 Octets 14 (template 44) 14 (temp 45), 14 (temp 46), 15 (temp 47),14 and 25 (temp 48)
Parameters
[in] key - GRIB2 character short key for type of intervals from Table 4.91
[out] value - corresponding GRIB2 value from Table 4.91
[out] ierr - error messages
Author
V. Krishna Kumar ORG: W/NP12
Date
2010-04-03
Definition at line 1466 of file grib2_all_tables_module.f90.
References maxtypeofintvls, and table4_91.
Referenced by g2sec4_temp44(), and g2sec4_temp48().
get_g2_typeoforigfieldvals()
subroutine grib2_all_tables_module::get_g2_typeoforigfieldvals (character(len=*) key, integer value, integer ierr)
This subroutine returns the corresponding GRIB2 - Table 5.1 Type of Original Field Values for a given short key name based on GRIB2 - Table 5.1.
Parameters
[in] key - GRIB2 character short key for type of original field values based on Table 5.1
[out] value - corresponding GRIB2 - Table 5.1 value
[out] ierr - error messages
Author
V. Krishna Kumar ORG: W/NP12
Date
2010-03-08
Definition at line 1576 of file grib2_all_tables_module.f90.
References maxtypeoforigfieldval, and table5_1.
get_g2_typeofprecip()
subroutine grib2_all_tables_module::get_g2_typeofprecip (character(len=*) key, integer value, integer ierr)
This subroutine returns the corresponding GRIB2 type of precipitation for a given short key name based on Table 4.201.
Parameters
[in] key GRIB2 character short key for type of precipitation
[out] value corresponding GRIB2 type of precipitation value from table 4.201
[out] ierr error messages
Author
Boi Vuong
Date
2019-07-01
Definition at line 2421 of file grib2_all_tables_module.f90.
References maxtypeofprecip, and table4_201.
get_g2_typeofprob()
subroutine grib2_all_tables_module::get_g2_typeofprob (character(len=*) key, integer value, integer ierr)
This subroutine returns the corresponding GRIB2 type of probability for a given short key name based on Table 4.9.
Parameters
[in] key - GRIB2 character short key for type of probability
[out] value - corresponding GRIB2 type of probability value from table 4.9
[out] ierr - error messages
Author
Boi Vuong ORG: EMC/EIB
Date
2019-07-01
Definition at line 2397 of file grib2_all_tables_module.f90.
References maxtypeofprob, and table4_9.
get_g2_typeoftimeintervals()
subroutine grib2_all_tables_module::get_g2_typeoftimeintervals (character(len=*) key, integer value, integer ierr)
This subroutine returns the corresponding GRIB2 - Type of time intervals value for a given short key name based on Table 4.11 of Section 4 Octets 48 (template 8) 61 (temp 9), 49 (temp 10), 51 (temp 11), 50 (temp 12), 82 (temp 13), 78 (tem p 14), 28 (temp 1001), and 40 (temp 1101)
Parameters
[in] key - GRIB2 character short key for type of statistical processing from Table 4.11
[out] value - corresponding GRIB2 value from Table 4.11
[out] ierr - error messages
Author
V. Krishna Kumar ORG: W/NP12
Date
2010-04-03
Definition at line 1441 of file grib2_all_tables_module.f90.
References maxtypeoftimeintvls, and table4_11.
Referenced by g2sec4_temp11(), g2sec4_temp12(), and g2sec4_temp8().
get_g2_unitoftimerange()
subroutine grib2_all_tables_module::get_g2_unitoftimerange (character(len=*) key, integer value, integer ierr)
This subroutine returns the corresponding GRIB2 - Indicator of unit of time range value for a given short key name based on Table 4.4 of Section 4, Octet 18.
Parameters
[in] key - GRIB2 character short key for indicator of unit of time range from Table 4.4
[out] value - corresponding GRIB2 value from Table 4.4
[out] ierr - error messages
Author
V. Krishna Kumar ORG: W/NP12
Date
2009-12-10
Definition at line 1358 of file grib2_all_tables_module.f90.
References maxunitoftimerange, and table4_4.
Referenced by g2sec4_temp0(), g2sec4_temp1(), g2sec4_temp11(), g2sec4_temp12(), g2sec4_temp44(), g2sec4_temp48(), and g2sec4_temp8().
get_g2_versionno()
subroutine grib2_all_tables_module::get_g2_versionno (character(len=*) key, integer value, integer ierr)
This subroutine returns the corresponding GRIB2 version number for a given short key name based on Table 1.0.
Parameters
[in] key - GRIB2 character short key for version number
[out] value - corresponding GRIB2 version number value from table 1.0
[out] ierr - error messages
Author
V. Krishna Kumar ORG: W/NP12
Date
2009-12-10
Definition at line 1213 of file grib2_all_tables_module.f90.
References maxver, and table1_0.
Referenced by g2sec1().
Variable Documentation
maxfixedsurfacetypes
integer, parameter grib2_all_tables_module::maxfixedsurfacetypes =200
Max fixed surface types.
Definition at line 45 of file grib2_all_tables_module.f90.
Referenced by get_g2_fixedsurfacetypes().
maxgenproc
integer, parameter grib2_all_tables_module::maxgenproc =250
maxgenproc
Definition at line 49 of file grib2_all_tables_module.f90.
Referenced by get_g2_on388genproc().
maxlocver
integer, parameter grib2_all_tables_module::maxlocver =20
maxlocver
Definition at line 31 of file grib2_all_tables_module.f90.
Referenced by get_g2_loctabversno().
maxordofsptdiff
integer, parameter grib2_all_tables_module::maxordofsptdiff =50
maxordofsptdiff
Definition at line 73 of file grib2_all_tables_module.f90.
Referenced by get_g2_ordofspcdiffvals().
maxorigincenters
integer, parameter grib2_all_tables_module::maxorigincenters =500
maxorigincenters
Definition at line 51 of file grib2_all_tables_module.f90.
Referenced by get_g2_on388origincenters().
maxprodstatus
integer, parameter grib2_all_tables_module::maxprodstatus =17
maxprodstatus
Definition at line 35 of file grib2_all_tables_module.f90.
Referenced by get_g2_prodstatus().
maxreftime
integer, parameter grib2_all_tables_module::maxreftime =15
maxreftime
Definition at line 33 of file grib2_all_tables_module.f90.
Referenced by get_g2_sigreftime().
maxstatprocesstypes
integer, parameter grib2_all_tables_module::maxstatprocesstypes =50
maxstatprocesstypes
Definition at line 59 of file grib2_all_tables_module.f90.
Referenced by get_g2_statprocesstypes().
maxsubcen
integer, parameter grib2_all_tables_module::maxsubcen =100
maxsubcen
Definition at line 27 of file grib2_all_tables_module.f90.
Referenced by get_g2_subcenters().
maxtypeofaerosol
integer, parameter grib2_all_tables_module::maxtypeofaerosol =200
maxtypeofaerosol
Definition at line 69 of file grib2_all_tables_module.f90.
Referenced by get_g2_typeofaerosol().
maxtypeofcluster
integer, parameter grib2_all_tables_module::maxtypeofcluster =100
maxtypeofcluster
Definition at line 67 of file grib2_all_tables_module.f90.
Referenced by get_g2_typeofcluster().
maxtypeofcompression
integer, parameter grib2_all_tables_module::maxtypeofcompression =50
maxtypeofcompression
Definition at line 55 of file grib2_all_tables_module.f90.
Referenced by get_g2_typeofcompression().
maxtypeofdata
integer, parameter grib2_all_tables_module::maxtypeofdata =100
maxtypeofdata
Definition at line 37 of file grib2_all_tables_module.f90.
Referenced by get_g2_typeofdata().
maxtypeofderivefcst
integer, parameter grib2_all_tables_module::maxtypeofderivefcst =100
maxtypeofderivefcst
Definition at line 43 of file grib2_all_tables_module.f90.
Referenced by get_g2_typeofderivefcst().
maxtypeofensfcst
integer, parameter grib2_all_tables_module::maxtypeofensfcst =100
maxtypeofensfcst
Definition at line 41 of file grib2_all_tables_module.f90.
Referenced by get_g2_typeofensfcst().
maxtypeofgenproc
integer, parameter grib2_all_tables_module::maxtypeofgenproc =100
maxtypeofgenproc
Definition at line 39 of file grib2_all_tables_module.f90.
Referenced by get_g2_typeofgenproc().
maxtypeofintvls
integer, parameter grib2_all_tables_module::maxtypeofintvls =50
maxtypeofintvls
Definition at line 71 of file grib2_all_tables_module.f90.
Referenced by get_g2_typeofintervals().
maxtypeoforigfieldval
integer, parameter grib2_all_tables_module::maxtypeoforigfieldval =15
maxtypeoforigfieldval
Definition at line 53 of file grib2_all_tables_module.f90.
Referenced by get_g2_typeoforigfieldvals().
maxtypeofpackingmethod
integer, parameter grib2_all_tables_module::maxtypeofpackingmethod =50
maxtypeofpackingmethod
Definition at line 57 of file grib2_all_tables_module.f90.
Referenced by get_g2_sec5packingmethod().
maxtypeofprecip
integer, parameter grib2_all_tables_module::maxtypeofprecip =100
maxtypeofprecip
Definition at line 65 of file grib2_all_tables_module.f90.
Referenced by get_g2_typeofprecip().
maxtypeofprob
integer, parameter grib2_all_tables_module::maxtypeofprob =100
maxtypeofprob
Definition at line 63 of file grib2_all_tables_module.f90.
Referenced by get_g2_typeofprob().
maxtypeoftimeintvls
integer, parameter grib2_all_tables_module::maxtypeoftimeintvls =50
maxtypeoftimeintvls
Definition at line 61 of file grib2_all_tables_module.f90.
Referenced by get_g2_typeoftimeintervals().
maxunitoftimerange
integer, parameter grib2_all_tables_module::maxunitoftimerange =30
maxunitoftimerange
Definition at line 47 of file grib2_all_tables_module.f90.
Referenced by get_g2_unitoftimerange().
maxver
integer, parameter grib2_all_tables_module::maxver =100
maxver
Definition at line 29 of file grib2_all_tables_module.f90.
Referenced by get_g2_versionno().
on388_table0
type(origin_centers), dimension(maxorigincenters) grib2_all_tables_module::on388_table0
ON388 Table.
Definition at line 819 of file grib2_all_tables_module.f90.
Referenced by get_g2_on388origincenters().
on388_tablea
type(gen_proc), dimension(maxgenproc) grib2_all_tables_module::on388_tablea
ON 388 Table A.
Definition at line 1050 of file grib2_all_tables_module.f90.
Referenced by get_g2_on388genproc().
table1_0
type(version_no), dimension(maxver) grib2_all_tables_module::table1_0
Table 1 0.
Definition at line 110 of file grib2_all_tables_module.f90.
Referenced by get_g2_versionno().
table1_1
type(local_table_vers_no), dimension(maxlocver) grib2_all_tables_module::table1_1
Table 1 1.
Definition at line 150 of file grib2_all_tables_module.f90.
Referenced by get_g2_loctabversno().
table1_2
type(sigreftime), dimension(maxreftime) grib2_all_tables_module::table1_2
Table 1 2.
Definition at line 169 of file grib2_all_tables_module.f90.
Referenced by get_g2_sigreftime().
table1_3
type(prod_status), dimension(maxprodstatus) grib2_all_tables_module::table1_3
Table 1 3.
Definition at line 186 of file grib2_all_tables_module.f90.
Referenced by get_g2_prodstatus().
table1_4
type(type_of_data), dimension(maxtypeofdata) grib2_all_tables_module::table1_4
table1_4
Definition at line 207 of file grib2_all_tables_module.f90.
Referenced by get_g2_typeofdata().
table4_10
type(statistical_processing_types), dimension(maxstatprocesstypes) grib2_all_tables_module::table4_10
table4_10
Definition at line 507 of file grib2_all_tables_module.f90.
Referenced by get_g2_statprocesstypes().
table4_11
type(type_of_time_intervals), dimension(maxtypeoftimeintvls) grib2_all_tables_module::table4_11
table4_11
Definition at line 550 of file grib2_all_tables_module.f90.
Referenced by get_g2_typeoftimeintervals().
table4_201
type(type_of_precip), dimension(maxtypeofprecip) grib2_all_tables_module::table4_201
table4_201
Definition at line 594 of file grib2_all_tables_module.f90.
Referenced by get_g2_typeofprecip().
table4_233
type(type_of_aerosol), dimension(maxtypeofaerosol) grib2_all_tables_module::table4_233
table4_233
Definition at line 617 of file grib2_all_tables_module.f90.
Referenced by get_g2_typeofaerosol().
table4_3
type(type_of_gen_proc), dimension(maxtypeofgenproc) grib2_all_tables_module::table4_3
table4_3
Definition at line 231 of file grib2_all_tables_module.f90.
Referenced by get_g2_typeofgenproc().
table4_4
type(unit_of_time_range), dimension(maxunitoftimerange) grib2_all_tables_module::table4_4
table4_4
Definition at line 276 of file grib2_all_tables_module.f90.
Referenced by get_g2_unitoftimerange().
table4_5
type(fixed_surface_types), dimension(maxfixedsurfacetypes) grib2_all_tables_module::table4_5
table4_5
Definition at line 299 of file grib2_all_tables_module.f90.
Referenced by get_g2_fixedsurfacetypes().
table4_6
type(type_of_ens_fcst), dimension(maxtypeofensfcst) grib2_all_tables_module::table4_6
table4_6
Definition at line 420 of file grib2_all_tables_module.f90.
Referenced by get_g2_typeofensfcst().
table4_7
type(type_of_derive_fcst), dimension(maxtypeofderivefcst) grib2_all_tables_module::table4_7
table4_7
Definition at line 436 of file grib2_all_tables_module.f90.
Referenced by get_g2_typeofderivefcst().
table4_8
type(type_of_cluster), dimension(maxtypeofcluster) grib2_all_tables_module::table4_8
table4_8
Definition at line 474 of file grib2_all_tables_module.f90.
Referenced by get_g2_typeofcluster().
table4_9
type(type_of_prob), dimension(maxtypeofprob) grib2_all_tables_module::table4_9
table4_9
Definition at line 488 of file grib2_all_tables_module.f90.
Referenced by get_g2_typeofprob().
table4_91
type(type_of_intervals), dimension(maxtypeofintvls) grib2_all_tables_module::table4_91
table4_91
Definition at line 570 of file grib2_all_tables_module.f90.
Referenced by get_g2_typeofintervals().
table5_0
type(type_of_packingmethod), dimension(maxtypeofpackingmethod) grib2_all_tables_module::table5_0
table5_0
Definition at line 799 of file grib2_all_tables_module.f90.
Referenced by get_g2_sec5packingmethod().
table5_1
type(type_of_orig_field_vals), dimension(maxtypeoforigfieldval) grib2_all_tables_module::table5_1
table5_1
Definition at line 753 of file grib2_all_tables_module.f90.
Referenced by get_g2_typeoforigfieldvals().
table5_40
type(type_of_compression), dimension(maxtypeofcompression) grib2_all_tables_module::table5_40
table5_40
Definition at line 787 of file grib2_all_tables_module.f90.
Referenced by get_g2_typeofcompression().
table5_6
type(order_of_sptdiff_vals), dimension(maxordofsptdiff) grib2_all_tables_module::table5_6
table5_6
Definition at line 775 of file grib2_all_tables_module.f90.
Referenced by get_g2_ordofspcdiffvals().
tablec
type(subcenters), dimension(maxsubcen) grib2_all_tables_module::tablec
tablec
Definition at line 81 of file grib2_all_tables_module.f90.
Referenced by get_g2_subcenters().