NCEPLIBS-g2tmpl: g2sec4_temp1.f90 File Reference
g2sec4_temp1.f90 File Reference
Returns the Grib2 Section 4 Template 4.11 list for given keys.
Functions/Subroutines
subroutine g2sec4_temp1 (icatg, iparm, typ_gen_proc_key, gen_proc_or_mod_key, hrs_obs_cutoff, min_obs_cutoff, unit_of_time_key, fcst_time, lvl_type1, scale_fac1, scaled_val1, lvl_type2, scale_fac2, scaled_val2, type_ens_fcst_key, perturb_num, num_fcst_ens, ipdstmpl1)
This subroutine returns the Grib2 Section 4 Template 4.1 list for given keys PDT 4.1 - Individual ensemble forecast, control and perturbed, at a horizontal level or in a horizontal layer at a point in time.
Detailed Description
Returns the Grib2 Section 4 Template 4.11 list for given keys.
Author
Boi Vuong
Date
2015-01-09
Definition in file g2sec4_temp1.f90.
Function/Subroutine Documentation
g2sec4_temp1()
subroutine g2sec4_temp1 (integer(4), intent(in) icatg, integer(4), intent(in) iparm, character(len=*), intent(in) typ_gen_proc_key, character(len=*), intent(in) gen_proc_or_mod_key, integer(4), intent(in) hrs_obs_cutoff, integer(4), intent(in) min_obs_cutoff, character(len=*), intent(in) unit_of_time_key, integer(4), intent(in) fcst_time, character(len=*), intent(in) lvl_type1, integer(4), intent(in) scale_fac1, integer(4), intent(in) scaled_val1, character(len=*), intent(in) lvl_type2, integer(4), intent(in) scale_fac2, integer(4), intent(in) scaled_val2, character(len=*), intent(in) type_ens_fcst_key, integer(4), intent(in) perturb_num, integer(4), intent(in) num_fcst_ens, integer(4), dimension(18), intent(inout) ipdstmpl1)
This subroutine returns the Grib2 Section 4 Template 4.1 list for given keys PDT 4.1 - Individual ensemble forecast, control and perturbed, at a horizontal level or in a horizontal layer at a point in time.
Parameters
[in] icatg Parameter category (see Code table 4.1)
[in] iparm Parameter number (see Code table 4.2)
[in] typ_gen_proc_key Type of generating process (see Code table 4.3)
[in] gen_proc_or_mod_key Analysis or forecast generating process identified (see Code ON388 Table A)
[in] hrs_obs_cutoff Hours of observational data cutoff after reference time (see Note)
[in] min_obs_cutoff Minutes of observational data cutoff after reference time (see Note)
[in] unit_of_time_key Indicator of unit of time range (see Code table 4.4)
[in] fcst_time Forecast time in units defined by octet 18
[in] lvl_type1 Type of first fixed surface (see Code table 4.5)
[in] scale_fac1 Scale factor of first fixed surface
[in] scaled_val1 Scaled value of first fixed surface
[in] lvl_type2 Type of second fixed surfaced (see Code table 4.5)
[in] scale_fac2 Scale factor of second fixed surface
[in] scaled_val2 Scaled value of second fixed surfaces
[in] type_ens_fcst_key Type of ensemble forecast (see Code table 4.6)
[in] perturb_num Perturbation ensemble number
[in] num_fcst_ens number of forecasts in ensemble
[out] ipdstmpl1 GRIB2 PDS Template 4.1 listing
Author
Boi Vuong
Date
2015-01-09
Definition at line 30 of file g2sec4_temp1.f90.
References grib2_all_tables_module::get_g2_fixedsurfacetypes(), grib2_all_tables_module::get_g2_on388genproc(), grib2_all_tables_module::get_g2_typeofensfcst(), grib2_all_tables_module::get_g2_typeofgenproc(), and grib2_all_tables_module::get_g2_unitoftimerange().