name: MacOS
on:
  push:
    branches:
    - develop
  pull_request:
    branches:
    - develop

jobs:
  MacOS:
    runs-on: macos-latest
    env:
      FC: gfortran-11
      CC: gcc-11

    steps:

    - name: checkout
      uses: actions/checkout@v4
      with: 
        path: g2tmpl

    - name: build
      run: |
        cd g2tmpl
        mkdir build 
        cd build
        cmake ..
        make -j2
    
    - name: test
      run: |
        cd $GITHUB_WORKSPACE/g2tmpl/build
        ctest --verbose --output-on-failure --rerun-failed 

