name: macOS Build
on: [push, pull_request]

jobs:
  macOS-build:
    runs-on: macos-latest
    env:
      FC: gfortran-9
      CC: gcc-9

    steps:

    - name: checkout
      uses: actions/checkout@v2
      with: 
        path: g2tmpl

    - name: build
      run: |
        cd g2tmpl
        mkdir build 
        cd build
        cmake ..
        make -j2
    
    - name: test
      run: |
        cd $GITHUB_WORKSPACE/g2tmpl/build
        ctest --verbose --output-on-failure        

