name: MacOS
on:
  push:
    branches:
    - develop
  pull_request:
    branches:
    - develop
  schedule:
    # Run monthly
    - cron: '0 0 1 * *'
  workflow_dispatch:

# Cancel in-progress workflows when pushing to a branch
concurrency:
  group: ${{ github.workflow }}-${{ github.event.pull_request.number || github.ref }}
  cancel-in-progress: true

jobs:
  MacOS:
    runs-on: macos-latest
    env:
      FC: gfortran-14
      CC: clang
      CXX: clang++
      
    steps:

    - name: checkout
      uses: actions/checkout@v4

    - name: build
      run: |
        cmake -B build
        cmake --build build --parallel 2 --verbose
    
    - name: test
      run: |
        ctest --test-dir build --verbose --output-on-failure --rerun-failed 

